Controllers/CustomerCartController.cs
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;
using TgiApplications.Models;
using TgiApplications.Utility;
using TgiApplications.ViewModels;

namespace TgiApplications.Controllers
{
    public class CustomerCartController : Controller
    {

        public OrderDetailsCart detailCart { get; set; }

        public ActionResult Index()
        {
            var _db = new TgiDbContext();
            detailCart = new OrderDetailsCart()
            {

                OrderHeader = new TgiApplications.Models.Order()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var userId = Session["UserID"].ToString();
            var cart = _db.ShoppingCarts.Where(c => c.ApplicationUserId == userId);
            if(cart !=null)
            {
                detailCart.listCart = cart.ToList();
            }

            foreach(var list in detailCart.listCart)
            {
                list.Service = _db.Services.FirstOrDefault(m => m.ServiceId == list.ServiceId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.Service.Price * list.Count);
                list.Service.ServiceDescription = SD.ConvertToRawHtml(list.Service.ServiceDescription);
                if(list.Service.ServiceDescription.Length>100)
                {
                    list.Service.ServiceDescription = list.Service.ServiceDescription.Substring(0, 99) + "...";
                }
            }
            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;
            
            if(Session[SD.ssCouponCode] !=null)
            {
                detailCart.OrderHeader.CouponCode = Session[SD.ssCouponCode].ToString();
                var couponFromDb = _db.Coupons.Where(c => c.Name.ToLower() == detailCart.OrderHeader.CouponCode.ToLower()).FirstOrDefault();
                detailCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            }


            return View(detailCart);

        }


        public ActionResult Summary()
        {
            var _db = new TgiDbContext();
            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new TgiApplications.Models.Order()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var userId = Session["UserID"].ToString();
            ApplicationUser applicationUser = _db.Users.Where(c => c.Id == userId).FirstOrDefault();
            var cart = _db.ShoppingCarts.Where(c => c.ApplicationUserId == userId);
            if (cart != null)
            {
                detailCart.listCart = cart.ToList();
            }

            foreach (var list in detailCart.listCart)
            {
                list.Service = _db.Services.FirstOrDefault(m => m.ServiceId == list.ServiceId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.Service.Price * list.Count);
               
            }
            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;
            detailCart.OrderHeader.PickupName = applicationUser.UserName;
            detailCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
            detailCart.OrderHeader.PickUpTime = DateTime.Now;


            if (Session[SD.ssCouponCode] != null)
            {
                detailCart.OrderHeader.CouponCode = Session[SD.ssCouponCode].ToString();
                var couponFromDb = _db.Coupons.Where(c => c.Name.ToLower() == detailCart.OrderHeader.CouponCode.ToLower()).FirstOrDefault();
                detailCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            }


            return View(detailCart);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Summary(string stripeToken)
        {
            var _db = new TgiDbContext();
            var userId = Session["UserID"].ToString();

            detailCart.listCart = _db.ShoppingCarts.Where(c => c.ApplicationUserId == userId).ToList();

            detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            detailCart.OrderHeader.OrderDate = DateTime.Now;
            detailCart.OrderHeader.UserId = userId;
            detailCart.OrderHeader.Status = SD.PaymentStatusPending;
            detailCart.OrderHeader.PickUpTime = Convert.ToDateTime(detailCart.OrderHeader.PickUpDate.ToShortDateString() + " " + detailCart.OrderHeader.PickUpTime.ToShortTimeString());

            List<OrderDetails> orderDetailsList = new List<OrderDetails>();
            _db.Orders.Add(detailCart.OrderHeader);
            _db.SaveChanges();

            detailCart.OrderHeader.OrderTotalOriginal = 0;


            foreach (var item in detailCart.listCart)
            {
                item.Service =  _db.Services.FirstOrDefault(m => m.ServiceId == item.ServiceId);
                OrderDetails orderDetails = new OrderDetails
                {
                    ServiceId = item.ServiceId,
                    OrderId = detailCart.OrderHeader.OrderId,
                    Description = item.Service.ServiceDescription,
                    Name = item.Service.ServiceName,
                    ItemId = item.Service.ItemId,
                    Price = item.Service.Price,
                    Count = item.Count
                };
                detailCart.OrderHeader.OrderTotalOriginal += orderDetails.Count * orderDetails.Price;
                _db.OrderDetails.Add(orderDetails);

            }

            if (Session[SD.ssCouponCode] != null)
            {
                detailCart.OrderHeader.CouponCode = Session[SD.ssCouponCode].ToString();
                var couponFromDb = _db.Coupons.Where(c => c.Name.ToLower() == detailCart.OrderHeader.CouponCode.ToLower()).FirstOrDefault();
                detailCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            }
            else
            {
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotalOriginal;
            }
            detailCart.OrderHeader.CouponCodeDiscount = detailCart.OrderHeader.OrderTotalOriginal - detailCart.OrderHeader.OrderTotal;

            _db.ShoppingCarts.RemoveRange(detailCart.listCart);
            Session[SD.ssCouponCode] = 0;
         var rs = _db.SaveChangesAsync();

            //var options = new ChargeCreateOptions
            //{
            //    Amount = Convert.ToInt32(detailCart.OrderHeader.OrderTotal * 100),
            //    Currency = "Naira",
            //    Description = "Order ID : " + detailCart.OrderHeader.OrderId,
            //    Source = stripeToken

            //};
            //var service = new ChargeService();
            //Charge charge = service.Create(options);

            //if (charge.BalanceTransactionId == null)
            //{
            //    detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            //}
            //else
            //{
            //    detailCart.OrderHeader.TransactionId = charge.BalanceTransactionId;
            //}

            //if (charge.Status.ToLower() == "succeeded")
            //{
            //    detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
            //    detailCart.OrderHeader.Status = SD.StatusSubmitted;
            //}
            //else
            //{
            //    detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            //}

            //_db.SaveChangesAsync();
            if(rs.Result > 0)
            {
                detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
                detailCart.OrderHeader.Status = SD.StatusSubmitted;
            }
            else
            {
                detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            }
            return RedirectToAction("Index", "Home");

        }


        public ActionResult AddCoupon()
        {
            if (detailCart.OrderHeader.CouponCode == null)
            {
                detailCart.OrderHeader.CouponCode = "";
            }
            Session[SD.ssCouponCode] = detailCart.OrderHeader.CouponCode;

            return RedirectToAction("Index");
        }

        public ActionResult RemoveCoupon()
        {

            Session[SD.ssCouponCode] = string.Empty;

            return RedirectToAction("Index");
        }


        public ActionResult Plus(int cartId)
        {
            var _db = new TgiDbContext();
            var cart = _db.ShoppingCarts.FirstOrDefault(c => c.Id == cartId);
            cart.Count += 1;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Minus(int cartId)
        {
            var _db = new TgiDbContext();
            var cart = _db.ShoppingCarts.FirstOrDefault(c => c.Id == cartId);
            if (cart.Count == 1)
            {
                _db.ShoppingCarts.Remove(cart);
                _db.SaveChanges();

                var cnt = _db.ShoppingCarts.Where(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
                Session[SD.ssShoppingCartCount] = cnt;
            }
            else
            {
                cart.Count -= 1;
                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Remove(int cartId)
        {
            var _db = new TgiDbContext();
            var cart = _db.ShoppingCarts.FirstOrDefault(c => c.Id == cartId);

            _db.ShoppingCarts.Remove(cart);
            _db.SaveChanges();

            var cnt = _db.ShoppingCarts.Where(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
            Session[SD.ssShoppingCartCount] = cnt;
           

Views/CustomerCart/Index.cshtml
@model TgiApplications.ViewModels.OrderDetailsCart

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<style>
    .backgroundWhite {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
    }

    .backgroundWhiteBorder {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
        border: 1px solid #ddd;
    }

    .backgroundWhiteBorder10Padding {
        background-color: white;
        padding: 10px;
        border-radius: 10px;
        border: 1px solid #ddd;
    }

    .menu-filter-list li {
        display: inline-block;
        cursor: pointer;
        padding: 10px 20px 10px;
        text-transform: uppercase;
        background: #f5f5f5;
        border-radius: 5px;
        font-weight: 700;
        font-size: 13px;
        -moz-transition: all 0.3s;
        -o-transition: all 0.3s;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
        font-family: "Poppins",sans-serif;
    }

        .menu-filter-list li.is-checke, .menu-filter-list li:hover {
            background-color: #545b62;
            color: #fff;
        }
</style>
@using (Html.BeginForm("Summary", "CustomerCart", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    if (Model.listCart.Count > 0)
    {
        <br />
        <input id="userId" asp-for="@Model.listCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Shopping Cart
                        </div>
                        <div class="col-6 text-right">
                            <a href="/Customer/index/" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.listCart)
                        {
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                    <img src="/UploadedImages/@item.Service.Image" class="rounded" width="120" height="80" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h4><strong>@item.Service.ServiceName</strong></h4>
                                    <h4><small>@item.Service.ServiceDescription</small></h4>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>$@item.Service.Price <span class="text-muted">x</span> @item.Count </strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            @*<button type="submit" class="btn btn-primary" asp-action="plus" asp-route-cartId="@item.ServiceId">
                                                <i class="fa fa-plus"></i>
                                            </button>*@
                                            <button type="button" onclick="add('@item.Id')" class="btn btn-success">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                        <div class="float-right mx-1">
                        
                                            <button type="button" onclick="minus('@item.Id')"  class="btn btn-primary">
                                                <i class="fa fa-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                        <button type="button" onclick="remove('@item.Id')" class="btn btn-outline-danger">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        @*<button type="submit" class="btn btn-outline-danger" asp-action="remove" asp-route-cartId="@item.ServiceId">
                                            <i class="fa fa-trash"></i>
                                        </button>*@
                                    </div>
                                </div>
                            </div>
                            <hr />
                        }

                        <div class="row">
                            <div class="col-12 col-md-5">
                                <div class="row">
                                    <div class="col-7">
                                        <input asp-for="@Model.OrderHeader.CouponCode" id="txtCouponCode" class="form-control" placeholder="coupon code..." />
                                    </div>
                                    <div class="col-5" style="margin-top:2px;">
                                        <button type="submit" class="btn btn-sm form-control btn-outline-success" id="btnCoupon" asp-action="AddCoupon">
                                            Apply
                                        </button>
                                        <button type="submit" class="btn btn-sm form-control btn-outline-danger" style="display:none" id="btnRemoveCoupon" asp-action="RemoveCoupon">
                                            Remove
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info"> Total (NAIRA)</span>
                                        <strong class="text-info">N <span id="txtOrderTotal">@Model.OrderHeader.OrderTotal</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>


                    </div>
                    <div class="card-footer">
                        <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                            <input type="submit" class="btn btn-success form-control" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="backgroundWhiteBorder"> No items added to the shopping cart...</div>
    }
}


@section Scripts{
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <script>
        $(function () {
            var couponCode = document.getElementById("txtCouponCode").value;

            if (couponCode.length > 0) {
                document.getElementById('btnCoupon').style.display = 'none';
                document.getElementById('btnRemoveCoupon').style.display = '';
            }
            else {
                document.getElementById('btnCoupon').style.display = '';
                document.getElementById('btnRemoveCoupon').style.display = 'none';
            }
        });
        function minus(cartId) {
            $.ajax({
                url: '/CustomerCart/Minus?cartId=' + cartId,
                type: 'GET',
                async: false,
                data: { 'cartId': cartId }
            });
            location.href = location.href;
        }
        function add(cartId) {
            $.ajax({
                url: '/CustomerCart/Plus?cartId=' + cartId,
                type: 'GET',
                async: false,
                data: { 'cartId': cartId }
            });
            location.href = location.href;
        }
        function remove(cartId) {
            $.ajax({
                url: '/CustomerCart/Remove?cartId=' + cartId,
                type: 'GET',
                async: false,
                data: { 'cartId': cartId }
            });
            location.href = location.href;
        }
    </script>
}

Views/CustomerCart/Summary.cshtml
@model TgiApplications.ViewModels.OrderDetailsCart
@using Microsoft.Extensions.Options

@*@inject IOptions<TgiApplications.Utility.StripeSettings> Stripe*@

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<style>

    .backgroundWhite {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
    }

    .backgroundWhiteBorder {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
        border: 1px solid #ddd;
    }

    .backgroundWhiteBorder10Padding {
        background-color: white;
        padding: 10px;
        border-radius: 10px;
        border: 1px solid #ddd;
    }

    .menu-filter-list li {
        display: inline-block;
        cursor: pointer;
        padding: 10px 20px 10px;
        text-transform: uppercase;
        background: #f5f5f5;
        border-radius: 5px;
        font-weight: 700;
        font-size: 13px;
        -moz-transition: all 0.3s;
        -o-transition: all 0.3s;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
        font-family: "Poppins",sans-serif;
    }

        .menu-filter-list li.is-checke, .menu-filter-list li:hover {
            background-color: #545b62;
            color: #fff;
        }
</style>
@using (Html.BeginForm("Summary", "CustomerCart", FormMethod.Post))
{
    if (Model.listCart.Count > 0)
    {
        <br />
        <input id="userId" asp-for="@Model.listCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Order Summary
                        </div>
                        <div class="col-6 text-right">
                            <a href="/CustomerCart/Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class="row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">PickUp Details:</span>
                                        </h4>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickupName" id="txtName" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Phone</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PhoneNumber" id="txtPhone" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Date</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpDate" id="datepicker" value="" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Time</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpTime" id="timepicker" value="" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Additional Instructions: </label>
                                        </div>
                                        <div class="col-9">
                                            <textarea asp-for="@Model.OrderHeader.Comments" style="height:100px;" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-5 offset-lg-1">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Order Summary:</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        @{ var total = 0.0;}

                                        @foreach (var details in Model.listCart)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div>
                                                    <h6 class="my-0">@details.Service.ServiceName</h6>
                                                    <small class="text-muted">Quantity: @details.Count</small>
                                                </div>
                                                <span class="text-muted">NAIRA@(details.Service.Price * details.Count)</span>
                                                @{ total += (details.Service.Price * details.Count); }
                                            </li>
                                        }
                                        @if (Model.OrderHeader.CouponCode != null)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div class="text-success">
                                                    <h6 class="my-0">Promo Code</h6>
                                                    <small class="text-success">@Model.OrderHeader.CouponCode</small>
                                                </div>
                                                <span class="text-success">-N@(total - Model.OrderHeader.OrderTotal)</span>
                                            </li>
                                        }
                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <small class="text-info">Total (NAIRA)</small>
                                            <strong class="text-info">NAIRA@(Model.OrderHeader.OrderTotal)</strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-4 offset-md-8">

                                @{
                                    var OrderTotalForStrip = Model.OrderHeader.OrderTotal * 100;
                                }
                                <!--<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"-->
                                        @*data-key="@Stripe.Value.PublishableKey"*@
                                        <!--data-amount="@OrderTotalForStrip"
                                        data-name="Spice Restaurant"
                                        data-label="Place Order"
                                        data-description="Good Food, Good Mood."
                                        data-locale="auto"
                                        data-allow-remember-me="false"
                                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png">
                                </script>
                                <script>
                                    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                                </script>-->
                                <button type="submit" id="btnPlaceOrder" onclick="return validateInput()" value="Place Order" class="btn btn-success form-control">Place Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="backgroundWhiteBorder"> No items added to the shopping cart...</div>
    }
}


@section Scripts{
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <script>
        $(function () {

            var minDt = 0;
            if (getTimeFromCurrentDate() >= "20.00") {
                minDt = 1;
            }


            $("#datepicker").datepicker({ minDate: minDt, maxDate: "+1W" });
            $("#timepicker").timepicker({ 'minTime': '11:00 AM', 'maxTime': '9:00 PM', step: '30' })
        });




        function setPickUpTime() {
            var dateSelected = document.getElementById("datepicker").value;
            var dt = new Date(dateSelected);
            var today = new Date();

            dt.setHours(0, 0, 0, 0);
            if (dt > today) {
                selectedTime = '11:00am';
            }
            else {
                selectedTime = getTimeFromCurrentDate();
            }

            $('#timepicker').timepicker('option', 'minTime', selectedTime);

        }


        function getTimeFromCurrentDate() {
            var curDt = new Date();

            var minTime = "";
            if (curDt.getHours() < 11) {
                minTime = '12:00pm';
            }
            else {
                if (curDt.getMinutes() < 30) {
                    minTime = (curDt.getHours() + 1).toString() + ':30pm'
                }
                else {
                    minTime = (curDt.getHours() + 2).toString() + ':00pm'
                }
            }
            return minTime;
        }

        $('#datepicker').change(function () {
            setPickUpTime();
        });

        function validateInput() {
            var time = document.getElementById("timepicker").value;
            var dt = document.getElementById("datepicker").value;
            var name = document.getElementById("txtName").value;
            var phone = document.getElementById("txtPhone").value;
            alert("Order Total Charges =N=@(Model.OrderHeader.OrderTotal * 100)")

            if (dt.toString().length == 0) {
                alert("Please select pickup date")
                return false;
            }
            else if (time.toString().length == 0) {
                alert("Please select pickup time")
                return false;
            }
            else if (name.toString().length == 0) {
                alert("Please enter pickup name")
                return false;
            }
            else if (phone.toString().length == 0) {
                alert("Please enter a phone number")
                return false;
            }
            else {
                return true;
            }
        }

    </script>
}