Controllers/CustomerOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using TgiApplications.Models;
using TgiApplications.Utility;
using TgiApplications.ViewModels;

namespace TgiApplications.Controllers
{
    public class CustomerOrderController : Controller
    {
 
        private int PageSize = 2;


        //[Authorize]
        public ActionResult ConfirmOrder(int id)
        {
            var _db = new TgiDbContext();
            var userId = Session["UserID"].ToString();

            OrderDetailsViewModel orderDetailsViewModel = new OrderDetailsViewModel()
            {
                OrderHeader = _db.Orders.Include("Users").FirstOrDefault(o => o.OrderId == id && o.UserId == userId),
                OrderDetails = _db.OrderDetails.Where(o => o.OrderId == id).ToList()
            };

            return View(orderDetailsViewModel);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetOrderStatus(int Id)
        {
            var _db = new TgiDbContext();
            return PartialView("_OrderStatus", _db.Orders.Where(m => m.OrderId == Id).FirstOrDefault().Status);

        }

       // [Authorize]
        public ActionResult OrderHistory(int productPage=1)
        {
            var _db = new TgiDbContext();
            var userId = Session["UserID"].ToString();

            OrderListViewModel orderListVM = new OrderListViewModel()
            {
                Orders = new List<OrderDetailsViewModel>()
            };

            

            List<Order> OrderHeaderList = _db.Orders.Include("Users").Where(u => u.UserId == userId).ToList();

            foreach (Order item in OrderHeaderList)
            {
                OrderDetailsViewModel individual = new OrderDetailsViewModel
                {
                    OrderHeader = item,
                    OrderDetails = _db.OrderDetails.Where(o => o.OrderId == item.OrderId).ToList()
                };
                orderListVM.Orders.Add(individual);
            }

            var count = orderListVM.Orders.Count;
            orderListVM.Orders = orderListVM.Orders.OrderByDescending(p => p.OrderHeader.OrderId)
                                 .Skip((productPage - 1) * PageSize)
                                 .Take(PageSize).ToList();

            orderListVM.PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                ItemsPerPage = PageSize,
                TotalItem = count,
                urlParam = "/CustomerOrder/OrderHistory?productPage=:"
            };

            return View(orderListVM);
        }

       // [Authorize(Roles = SD.LaundryUser + "," + SD.ManagerUser)]
        public ActionResult ManageOrder(int productPage = 1)
        {
            var _db = new TgiDbContext();
            List<OrderDetailsViewModel> orderDetailsVM = new List<OrderDetailsViewModel>();

            List<Order> OrderHeaderList = _db.Orders.Where(o=>o.Status==SD.StatusSubmitted || o.Status==SD.StatusInProcess).OrderByDescending(u=>u.PickUpTime).ToList();
            

            foreach (Order item in OrderHeaderList)
            {
                OrderDetailsViewModel individual = new OrderDetailsViewModel
                {
                    OrderHeader = item,
                    OrderDetails = _db.OrderDetails.Where(o => o.OrderId == item.OrderId).ToList()
                };
                orderDetailsVM.Add(individual);
            }

            

            return View(orderDetailsVM.OrderBy(o=>o.OrderHeader.PickUpTime).ToList());
        }


        public ActionResult GetOrderDetails(int Id)
        {
            var _db = new TgiDbContext();
            OrderDetailsViewModel orderDetailsViewModel = new OrderDetailsViewModel()
            {
                OrderHeader = _db.Orders.Include("Users").FirstOrDefault(m => m.OrderId == Id),
                OrderDetails = _db.OrderDetails.Where(m => m.OrderId == Id).ToList()
            };
            //orderDetailsViewModel.OrderHeader.ApplicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(u => u.Id == orderDetailsViewModel.OrderHeader.UserId);

            return PartialView("_IndividualOrderDetails", orderDetailsViewModel);
        }




        //[Authorize(Roles =SD.LaundryUser + ","+ SD.ManagerUser)]
        public ActionResult OrderPrepare(int OrderId)
        {
            var _db = new TgiDbContext();
            Order orderHeader =  _db.Orders.Find(OrderId);
            orderHeader.Status = SD.StatusInProcess;
            _db.SaveChanges();
            return RedirectToAction("ManageOrder", "Order");
        }


        //[Authorize(Roles = SD.LaundryUser + "," + SD.ManagerUser)]
        public ActionResult OrderReady(int OrderId)
        {
            var _db = new TgiDbContext();
            Order orderHeader =  _db.Orders.Find(OrderId);
            orderHeader.Status = SD.StatusReady;
            _db.SaveChanges();

            //Email logic to notify user that order is ready for pickup
            //await _emailSender.SendEmailAsync(_db.Users.Where(u => u.Id == orderHeader.UserId).FirstOrDefault().Email, "Spice - Order Ready for Pickup " + orderHeader.Id.ToString(), "Order is ready for pickup.");


            return RedirectToAction("ManageOrder", "Order");
        }


        //[Authorize(Roles = SD.LaundryUser + "," + SD.ManagerUser)]
        public ActionResult OrderCancel(int OrderId)
        {
            var _db = new TgiDbContext();
            Order orderHeader = _db.Orders.Find(OrderId);
            orderHeader.Status = SD.StatusCancelled;
            _db.SaveChangesAsync();
            //_emailSender.SendEmailAsync(_db.Users.Where(u => u.Id == orderHeader.UserId).FirstOrDefault().Email, "Spice - Order Cancelled " + orderHeader.Id.ToString(), "Order has been cancelled successfully.");

            return RedirectToAction("ManageOrder", "Order");
        }



        //[Authorize]
        public ActionResult OrderPickup(int productPage = 1, string searchEmail=null, string searchPhone = null, string searchName = null)
        {
            var _db = new TgiDbContext();


            OrderListViewModel orderListVM = new OrderListViewModel()
            {
                Orders = new List<OrderDetailsViewModel>()
            };

            StringBuilder param = new StringBuilder();
            param.Append("/CustomerOrder/OrderPickup?productPage=:");
            param.Append("&searchName=");
            if(searchName!=null)
            {
                param.Append(searchName);
            }
            param.Append("&searchEmail=");
            if (searchEmail != null)
            {
                param.Append(searchEmail);
            }
            param.Append("&searchPhone=");
            if (searchPhone != null)
            {
                param.Append(searchPhone);
            }

            List<Order> OrderHeaderList = new List<Order>();
            if (searchName != null || searchEmail != null || searchPhone != null)
            {
                var user = new ApplicationUser();

                if(searchName!=null)
                {
                    OrderHeaderList = _db.Orders.Include("Users")
                                                .Where(u => u.PickupName.ToLower().Contains(searchName.ToLower()))
                                                .OrderByDescending(o => o.OrderDate).ToList();
                }
                else
                {
                    if (searchEmail != null)
                    {
                        user = _db.Users.Where(u => u.Email.ToLower().Contains(searchEmail.ToLower())).FirstOrDefault();
                        OrderHeaderList = _db.Orders.Include("Users")
                                                    .Where(o=>o.UserId==user.Id)
                                                    .OrderByDescending(o => o.OrderDate).ToList();
                    }
                    else
                    {
                        if (searchPhone != null)
                        {
                            OrderHeaderList = _db.Orders.Include("Users")
                                                        .Where(u => u.PhoneNumber.Contains(searchPhone))
                                                        .OrderByDescending(o => o.OrderDate).ToList();
                        }
                    }
                }
            }
            else
            {
                OrderHeaderList = _db.Orders.Include("Users").Where(u => u.Status == SD.StatusReady).ToList();
            }

            foreach (Order item in OrderHeaderList)
                {
                    OrderDetailsViewModel individual = new OrderDetailsViewModel
                    {
                        OrderHeader = item,
                        OrderDetails = _db.OrderDetails.Where(o => o.OrderId == item.OrderId).ToList()
                    };
                    orderListVM.Orders.Add(individual);
                }
            


            var count = orderListVM.Orders.Count;
            orderListVM.Orders = orderListVM.Orders.OrderByDescending(p => p.OrderHeader.OrderId)
                                 .Skip((productPage - 1) * PageSize)
                                 .Take(PageSize).ToList();

            orderListVM.PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                ItemsPerPage = PageSize,
                TotalItem = count,
                urlParam = param.ToString()
            };

            return View(orderListVM);
        }

        //[Authorize(Roles =SD.FrontDeskUser + ","+ SD.ManagerUser)]
        [HttpPost]
        [ActionName("OrderPickup")]
        public ActionResult OrderPickupPost(int orderId)
        {
            var _db = new TgiDbContext();
            Order orderHeader = _db.Orders.Find(orderId);

Views/CustomerOrder/ConfirmOrder.cshtml
@model TgiApplications.ViewModels.OrderDetailsViewModel
@{
    ViewData["Title"] = "Confirm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="backgroundWhite">
    <div class="row px-3">
        <div class="col-8">
            <h2 class="text-info">Order Confirmed</h2>
        </div>
        <div class="col-4 text-right">
            <a href="/CustomerOrder/Index" class="btn btn-success form-control">New Order</a>
        </div>
    </div>

    @if (Model.OrderHeader != null)
    {
        <div style="color:maroon" class="p-3">
            Your order has been confirmed! Please see the order summary below.
            <br />
            Feel free to contact us if you have any questions.
        </div>
        @Html.Partial("_IndividualOrderDetails", Model)
    }
    else
    {
        <div class="text-danger">Error... Please try again.</div>
    }
</div>

Views/CustomerOrder/ManageOrder.cshtml
@model List<TgiApplications.ViewModels.OrderDetailsViewModel>
@using TgiApplications.Utility
@{
    ViewData["Title"] = "ManageOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<style>

    .backgroundWhite {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
    }

    .backgroundWhiteBorder {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
        border: 1px solid #ddd;
    }

    .backgroundWhiteBorder10Padding {
        background-color: white;
        padding: 10px;
        border-radius: 10px;
        border: 1px solid #ddd;
    }

    .menu-filter-list li {
        display: inline-block;
        cursor: pointer;
        padding: 10px 20px 10px;
        text-transform: uppercase;
        background: #f5f5f5;
        border-radius: 5px;
        font-weight: 700;
        font-size: 13px;
        -moz-transition: all 0.3s;
        -o-transition: all 0.3s;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
        font-family: "Poppins",sans-serif;
    }

        .menu-filter-list li.is-checke, .menu-filter-list li:hover {
            background-color: #545b62;
            color: #fff;
        }
</style>
<h2 class="text-info">Manage Order's</h2>
<form method="post">
    <br />
    @if (Model.Count > 0)
    {
        <div class="container row bg-white p-2 border mb-3 rounded">
            @foreach (var item in Model)
            {
                <div class="col-12 pb-3 pt-3">
                    <div class="backgroundWhiteBorder10Padding">
                        <div class="row">
                            <div class="col-lg-4 col-12">
                                Order Number : @item.OrderHeader.OrderId
                                <ul class="text-info">
                                    @foreach (var details in item.OrderDetails)
                                    {
                                        <li>@details.Name x @details.Count</li>
                                    }
                                </ul>
                            </div>
                            <div class="col-lg-4 col-12 pb-2">
                                <div class="input-group pb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text">Time</span>
                                    </div>
                                    <input type="text" class="border rounded form-control" readonly value="@item.OrderHeader.PickUpTime" />
                                </div>
                                @{
                                    var comments = item.OrderHeader.Comments;
                                    if (comments == null || comments.Trim().Length == 0)
                                    {
                                        item.OrderHeader.Comments = "No Instructions";
                                    }

                                }
                                <textarea asp-for="@item.OrderHeader.Comments" readonly class="rounded border form-control" style="width:100%;height:75px;"></textarea>
                            </div>
                            <div class="col-lg-4 col-12 d-flex align-content-center">
                                @if (item.OrderHeader.Status.Equals(SD.StatusSubmitted))
                                {
                                    <div class="col-12">
                                        <button type="submit" asp-action="OrderPrepare" asp-route-OrderId="@item.OrderHeader.OrderId" class="btn btn-info form-control mb-3">
                                            <i class="fa fa-check"></i> &nbsp; Start Washing
                                        </button>
                                        <button type="submit" asp-action="OrderCancel" asp-route-OrderId="@item.OrderHeader.OrderId" class="btn btn-danger form-control mb-3">
                                            <i class="fa fa-times"></i> &nbsp; Cancel Order
                                        </button>
                                    </div>
                                }
                                else
                                {
                                    if (item.OrderHeader.Status.Equals(SD.StatusInProcess))
                                    {
                                        <div class="col-12">
                                            <button type="submit" asp-action="OrderReady" asp-route-OrderId="@item.OrderHeader.OrderId" class="btn btn-success form-control mb-3">
                                                <i class="fa fa-flag-checkered"></i> &nbsp; Order Ready
                                            </button>
                                            <button type="submit" asp-action="OrderCancel" asp-route-OrderId="@item.OrderHeader.OrderId" class="btn btn-danger form-control mb-3">
                                                <i class="fa fa-times"></i> &nbsp; Cancel Order
                                            </button>
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</form>

Views/CustomerOrder/OrderPickup.cshtml
@model TgiApplications.ViewModels.OrderListViewModel
@using TgiApplications.Utility
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<style>

    .backgroundWhite {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
    }

    .backgroundWhiteBorder {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        margin-bottom: 30px;
        border: 1px solid #ddd;
    }

    .backgroundWhiteBorder10Padding {
        background-color: white;
        padding: 10px;
        border-radius: 10px;
        border: 1px solid #ddd;
    }

    .menu-filter-list li {
        display: inline-block;
        cursor: pointer;
        padding: 10px 20px 10px;
        text-transform: uppercase;
        background: #f5f5f5;
        border-radius: 5px;
        font-weight: 700;
        font-size: 13px;
        -moz-transition: all 0.3s;
        -o-transition: all 0.3s;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
        font-family: "Poppins",sans-serif;
    }

        .menu-filter-list li.is-checke, .menu-filter-list li:hover {
            background-color: #545b62;
            color: #fff;
        }
</style>
@using (Html.BeginForm("OrderPickup", "CustomerOrder", FormMethod.Get))
{
    <br />
    <br />
    <h2 class="text-info"> Orders Ready for Pickup : </h2>
    <div class="border backgroundWhite">
        <div class="container border border-secondary" style="height:60px;">
            <div class="row container">
                <div class="col-11">
                    <div class="row" style="padding-top:10px">
                        <div class="col-4">
                            @Html.Editor("searchName", new { htmlAttributes = new { @class = "form-control", @placeholder = "Name..." } })
                        </div>
                        <div class="col-4">
                            @Html.Editor("searchPhone", new { htmlAttributes = new { @class = "form-control", @placeholder = "Phone..." } })
                        </div>
                        <div class="col-4">
                            @Html.Editor("searchEmail", new { htmlAttributes = new { @class = "form-control", @placeholder = "Email..." } })
                        </div>
                    </div>
                </div>
                <div class="col-1">
                    <div class="row" style="padding-top:10px;">
                        <button type="submit" name="submit" value="Search" class="btn btn-info form-control">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>

        </div>
        <br />
        <div>
            @if (Model.Orders.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            @Html.DisplayNameFor(m => m.Orders[0].OrderHeader.OrderId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Orders[0].OrderHeader.PickupName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Orders[0].OrderHeader.ApplicationUser.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Orders[0].OrderHeader.PickUpTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Orders[0].OrderHeader.OrderTotal)
                        </th>
                        <th>
                            Total Items
                        </th>
                        <th></th>

                    </tr>
                    @foreach (var item in Model.Orders)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.OrderHeader.OrderId)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.OrderHeader.PickupName)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.OrderHeader.ApplicationUser.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.OrderHeader.PickUpTime)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.OrderHeader.OrderTotal)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.OrderDetails.Count)
                            </td>
                            <td>
                                <button type="button" class="btn btn-success anchorDetail" data-id="@item.OrderHeader.OrderId" data-toggle="modal">
                                    <i class="fa fa-list-alt"></i> Details
                                </button>

                            </td>
                        </tr>
                    }
                </table>
                <div page-model="@Model.PagingInfo" page-classes-enabled="true" page-class="btn border"
                     page-class-normal="btn btn-light" page-class-selected="btn btn-info active"
                     class="btn-group float-right">
                </div>
                <br />
            }
            else
            {
                <p>No category exists...</p>
            }
        </div>
    </div>
}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog-centered modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-success text-light ">
                <div class="col-10 offset-1">
                    <center><h5 class="modal-title">Order Details</h5></center>
                </div>
                <div class="col-1">
                    <button type="button" class="float-right btn-outline-secondary close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <div class="modal-body justify-content-center" id="myModalContent">

            </div>

        </div>
    </div>
</div>



@section scripts
    {
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <script>
        var PostBackURL = '/CustomerOrder/GetOrderDetails';

        $(function () {
            $(".anchorDetail").click(function () {

                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');

                $.ajax({
                    type: "GET",
                    url: PostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    cache: false,
                    datatyype: "json",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        $('#myModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed");
                    }
                });

            });


        });
    </script>
}